### ISSUE TITLE
Extract numbers into constants.

### ISSUE THREAD

**Issue by totsteps** [DIT112-V19/group-10#25]
Should we extract numberical values into `constants`?

https://github.com/DIT112-V19/group-10/blob/0aee7afc4e9ecc9c39d504062c27c681d78d0d4d/src/obstacle_avoidance/obstacle_avoidance.ino#L25

https://github.com/DIT112-V19/group-10/blob/0aee7afc4e9ecc9c39d504062c27c681d78d0d4d/src/obstacle_avoidance/obstacle_avoidance.ino#L35

**Comment by armin2118** [comment]
I think we can set speed to a constant but we should probably leave the baud rate as a number even though it can be made a constant.
