### ISSUE TITLE
Integrate tests into Travis CI

### ISSUE THREAD

**Issue by ferenckata** [DIT112-V19/group-10#46]
## Description
As a car owner I want to make sure that the new code does not break the previous working version.

## Acceptance Criteria
Automated build by Travis CI runs all tests

**Comment by ferenckata** [comment]
Travis is added and runs the tests

**Comment by platisd** [comment]
@ferenckata cool! Do you know what would even be more cool? To add a coverage report showing you which parts of your code you have tested! I'd suggest you use [codecov.io](https://codecov.io/) for this. It's rather simple, you can check on how codecov is used in [this](https://github.com/platisd/indoor-navigation-system) or [this](https://github.com/platisd/smartcar_shield) projects.
