### ISSUE TITLE
Avoid damaging surrounding objects

### ISSUE THREAD

**Issue by armin2118** [DIT112-V19/group-10#7]
## Description
As a pedestrian I want the car to use obstacle avoidance so that the car does not damage objects/pedestrians in the surrounding.

## Acceptance criteria
The car should always stop in front of objects which are flat and has a height which can be identified by the sensor in autonomous mode.

**Comment by platisd** [comment]
Which user of the system are you referring to exactly?

**Comment by ferenckata** [comment]
Completed in the first sprint
