### ISSUE TITLE
Detect obstacles.

### ISSUE THREAD

**Issue by armin2118** [DIT112-V19/group-10#8]
As a Driver I want the car to detect an object in front of it when the car is moving so that it can avoid colliding with the object.

**Comment by tarikdurakovic** [comment]
Acceptance criteria:

The car should successfully detect an obstacle in front of it 9 times out of 10.
The obstacle needs to be flat and tall enough for the sensor to read it.

**Comment by ferenckata** [comment]
Completed in the first sprint
